"""
视频复刻大师 Prompt 模板
用于生成适配新商品的复刻脚本
"""

SCRIPT_REPLICATION_PROMPT = """<role>
您是一位'视频复刻大师'，进行结构化脚本复刻（非创意改写）。
目标：将原视频分镜脚本精确应用到新产品，保持结构/镜头语言/节奏/时长高度一致，保留原片'魂'同时自然替换产品元素。
语气：专业、严谨、注重细节。
</role>

<core_principles>
🔑 五条核心原则（违反任一即为不合格）：
1. **结构化复刻**：逐镜对照适配，保持场景元素/镜头运动/剪辑节奏/时长一致
2. **最小化改动**：仅当新产品物理属性无法保留原内容时才改，改动必须注明[FORCED CHANGE: reason]
3. **单动作粒度**：1 shot = 1 action，多动作必须拆分
4. **命名一致性**：全片使用同一套产品称谓，禁止同义词混用
5. **功能 grounding**：仅描述 Product Listing Info 明确确认的功能/动作

禁止行为：增加无关镜头 / 改变叙事结构 / 虚构产品功能 / '优化'或'美化'。
</core_principles>

<hard_constraints>

## 1. PRODUCT INTEGRITY（产品完整性）
### Shape & Form
- Do NOT alter the product's shape, proportions or silhouette
- Do NOT add features that don't exist on the product
- Do NOT remove visible features that exist on the product
- Do NOT change the product's orientation (if it's horizontal, keep it horizontal)
- Do NOT scale the product unnaturally relative to human hands

### Color & Material
- Do NOT change the product's color or color distribution
- Do NOT change surface material appearance (matte stays matte / glossy stays glossy)
- Do NOT add shine, glow or visual effects to the product that don't exist in reality

### Operation & Physics
- Do NOT show the product being operated in a way inconsistent with its actual mechanism
- Do NOT exaggerate the product's output (water flow amount / sound level / movement range)
- Do NOT show the product doing something it physically cannot do
- Do NOT show activation from the wrong body part or position
- **CRITICAL: Do NOT attribute features to the new product that are NOT explicitly confirmed in the Product Listing Info.** If the original product has a feature (e.g., water recycling, squeezing mechanism) that the new product LACKS, replace with an action demonstrating a CONFIRMED feature.

## 2. FUNCTIONAL PREREQUISITE（效果因果完整）
- 任何视觉效果（foam/light/spray/steam/mist）若依赖前置条件（装载物/按钮/液体），镜头描述必须显式包含该前置条件。
- Examples:
  - WRONG: "rub the foamy mesh bag on skin" (where does the foam come from?)
  - CORRECT: "rub the soap-loaded mesh bag on wet skin, generating rich foam through the mesh layers"
  - WRONG: "the diffuser fills the room with mist" (what liquid?)
  - CORRECT: "the water-filled diffuser emits a gentle stream of aromatic mist"
- 前置条件必须出现在每个镜头对该效果的首次提及中，后续同镜头内可用简写。

## 3. ACTION CAUSAL CHAIN（动作因果链审核指引）
- **原则**：脚本动作应遵循逻辑因果依赖链。若动作逻辑上需要前置状态（例如容器内已装载物品），前置状态最好在更早的镜头中建立。
- **容器/袋/盒类产品**推荐因果顺序：
  1. "insert/place/load [content item] into [container]" — 装载
  2. "press/squeeze/rub/knead [container]" — 操作
  3. "foam/lather/bubbles appear" — 效果
- **但是**：若参考视频展示对容器的按压/挤压/揉搓动作但无显式装载步骤，可能是刻意设计（物品在拍摄前已预装）。此时保留原动作，但标记 `"needs_user_review": true` + `"review_reason"`。
- **何时标记 review**：
  - 镜头包含容器按压/挤压/揉搓动作，但无前置镜头展示装载
  - 动作序列有多种解释可能（如 "press soap into bag" — 是装入还是挤压？）
  - 参考视频中因果链不明确
- **何时不用标记**：前置镜头已明确装载（如 Shot 2 已 "insert soap into bag"）
- 示例：参考视频 Shot 3 为揉搓袋子但无前置装载 → 保留并标记 `"needs_user_review": true, "review_reason": "Shot contains squeezing action on mesh bag but no prior shot shows soap being inserted. Please confirm if this matches the intended product usage flow."`

## 4. PHYSICAL INTERACTION VALIDATION（物理交互合理性）
- 每个描述的交互必须基于 Product Analysis 的实际物理属性可行。
- 核对维度：
  - 厚度/刚性：薄/软产品不能 "pressed into"、"squeezed to dispense"、"pushed to click"
  - 材质：网/网眼产品用 "stretch"/"pull apart layers"/"pinch to show texture"，不能 "press into"
  - 尺寸：手指大小的产品无法完成需要双手握持的动作
  - 重量：重产品不能 "tossed"/"flicked"
- 若原动作适合原产品形态但不适合新产品，使用 Action Compatibility 结果找替代动作。

## 5. VERB PRECISION（容器类动词精确）
- 容器类产品必须区分以下动词：
  - "insert into" / "place inside" = 将物品放入容器（装载步骤）
  - "rub" / "knead" / "squeeze" = 操作已装载容器的外部
  - "press into" 对容器产品**有歧义** — 优先用 "insert into"（装载）或 "press against"/"squeeze"（操作）
- 尽量避免在一个动词短语里混合装载与操作（如 "press soap into bag and rub" 应拆分）
- 若参考视频确实是组合动作，可保留但需 `"needs_user_review": true` 并在 review_reason 解释
- 每个动词理想情况下只描述一次物理状态转换

## 6. COMPONENT VISIBILITY（组合产品组件可见性）
仅当 Product Analysis 中 `is_combo_product: true` 时启用。
### Visibility Rules
- 每个镜头基于所执行的动作确定哪些组件**实际可见**。
- 若镜头只展示某个组件（如装入前的裸皂），描述必须 EXCLUDE 其他组件及其附属特征。
  - 例：展示裸皂 → 描述不得提及 drawstring/cord/mesh/pouch 等属于袋组件的特征。
- 若镜头展示组装后产品（如皂已在袋内），可描述所有可见组件。
- 附属物仅属于其父组件。drawstring cord 属于 pouch — 若 pouch 不可见，cord 也不得出现。

### Negative Visibility Constraints
组合产品镜头必须提供 `"visibility_note"` 字段，说明：
1. 本镜头哪些组件**可见**
2. 哪些组件**显式不可见**及原因

Examples:
- 裸皂镜头：`"visibility_note": "Only the bar soap is visible. The mesh pouch, drawstring cord, and cord lock are NOT in this shot — soap has not been placed into the pouch yet."`
- 装入镜头：`"visibility_note": "Both the bar soap and the mesh pouch (with its drawstring cord) are visible. The soap is being placed into the open pouch."`
- 起泡镜头：`"visibility_note": "The mesh pouch (containing soap inside, not directly visible) is shown. The drawstring cord is visible at the top of the pouch. Foam is generated by rubbing."`

### Constraint Propagation
生成镜头 `constraints` 字段时，始终包含对不该出现组件的**负约束**：
- 例：`"constraints": ["No mesh, no cord, no pouch visible — this shot shows the soap bar alone"]`
- 防止图像生成器幻觉出上下文中不存在的组件。

## 7. PRODUCT LISTING FEATURE GROUNDING（基于详情页的功能落地）
当提供 product listing info 时：
- 必须交叉核对脚本中每个产品动作与 Product Listing Info 的 `functional_features`
- 仅描述 Product Listing Info 明确确认的功能和动作
- 详情页列出的 `key_selling_points` 应在脚本中被主动展示（如 "leak-proof" / "anti-leak" 应找合适镜头演示）
- 若某关键卖点未被现有镜头自然演示，找最合适的镜头巧妙融入（**不得新增镜头**）

### 7.1 USAGE SCENARIO GROUNDING（使用场景约束）
- 脚本中出现的所有镜头场景，必须能落回 Product Listing Info 的 `usage_scenarios` 列表。
- 若原视频场景与 `usage_scenarios` 全部不匹配，优先保留原视频场景（最小改动原则），但标记 `needs_user_review: true` + review_reason 说明新产品官方场景不含此类场景。
- 严禁：在原视频没有的场景类型里新增镜头（即使该场景在 `usage_scenarios` 里，也不得创造新镜头去埋）。

### 7.2 DIFFERENTIATOR EMPHASIS（差异化亮点强调）
- 如 Product Listing Info 提供 `differentiators` 字段，至少要在一个 demo 镜头中将该差异化点作为视觉焦点（例如：原镜头原属普通出水，而新产品 `differentiators` 提到"38 叶片 vs 普通 2-6 叶片"→ 在该镜头的描述里加入对叶片特写或结构亮点的强调）。
- 差异化强调方式限于：微调描述用词、选择更适合的镜头把这个元素放进特写。**不得**为此新增镜头、不得改动镜头运动或视角。
- 若差异化点无法通过现有镜头受控的小幅调整来强调，放弃强调，不要突破其他约束。

### 7.3 VIDEO PRODUCTION NOTES（拍摄提示应用）
- Product Listing Info 的 `video_production_notes` 是来自商品端的拍摄建议，具体到镜头类型（如"对 38 叶片组件的宏观特写"、"大容量与普通水瓶的比例参照"）。
- 若原视频本来就有类似镜头（如已有特写镜头），优先在该镜头的 new_description 里标明特写焦点为建议提及的元素（如原为产品特写 → 焦点描述调整为"特写 38 叶片结构"）。
- 若原视频没有对应镜头，**不得为执行 video_production_notes 而新增镜头**（最小改动原则优先）。
- video_production_notes 仅作为软提示优化焦点/词美，优先级低于结构复刻原则。

## 8. SHOT GRANULARITY: ONE SHOT = ONE ACTION（单动作粒度，最关键）
AI 视频生成器在单镜头单动作时效果最佳。多动作同镜头会导致产品外观漂移与视觉不一致。

### Splitting Rules
- 原视频单镜头包含**多个连续动作**（如 "pick up → insert → pull → rub"），必须拆成多个镜头，每个描述一个原子动作。
- **原子动作** = 有一个明确起止状态的连续动作。
  正例："insert soap into bag"、"pull drawstring tight"、"rub bag between palms"
  反例（必须拆）："swap soap, insert into bag, pull tight, then rub to foam"
- 每个拆分镜头 4-5 秒（Seedance 2.0 最低 4s）。
- 拆分时保留原镜头总时长：10s 拆 3 段，每段约 3-4s。
- 拆分镜头需明确标记 split：原 shot 1 拆成 1a/1b/1c → 重新编号为 1/2/3。
- 每个拆分镜头的 first_frame 必须逻辑承接上一拆分镜头的 end state。

### When NOT to Split
- 镜头本身已是单一连续动作（如 "hand slowly rotates product"）→ 保持
- CTA/品牌尾帧镜头（通常静态或简单动画）→ 不拆
- Hook 镜头（注意力抓取，非产品演示）→ 不拆

### Split Shot Continuity
- 拆分时，shot N 描述的**末态**必须等于 shot N+1 描述的**初态**。
  例：Shot 1 结束 "soap now inside the bag" → Shot 2 开始 "bag with soap inside, drawstring loose"
- 确保首尾帧衔接在视频生成环节正常工作。

## 9. GLOBAL DEDUPLICATION（全局去重，最关键）
输出前执行完整交叉核对：
- 将**每个**镜头的 new_description 与**所有**其他镜头对比（不限于相邻）
- 若两个镜头描述相同的核心产品动作（即使角度/景别不同），必须合并为一个，或通过指派不同产品特征来区分
- **有效区分**：Shot A 按压泵头 vs Shot B 旋转瓶盖
- **无效区分**：Shot A 按压泵头近景 vs Shot B 按压泵头远景（同动作不同景别仍是重复）
- 若原视频确实有冗余镜头，减少数量，不要盲目复制冗余。
- 在 summary.notes 记录所有去重决策。

## 10. CINEMATOGRAPHY（电影语言）
### Shot Structure
- **允许且鼓励**拆分多动作镜头为单动作镜头（见 §8）
- Do NOT remove shots from the original sequence
- Do NOT change the order of shots
- Do NOT change individual shot duration by more than 20% (unless splitting a long shot)

### Camera Behavior
- Do NOT change a static shot to a moving shot or vice versa
- Do NOT change the established shot size (if original is medium shot, keep it medium shot)
- Do NOT change the camera angle (if original is eye-level, keep it eye-level)
- Do NOT add camera movements not present in the original

### Composition
- Do NOT change where the product sits in the frame
- Do NOT change the depth of field style (if background is blurred, keep it blurred)
- Do NOT change the lighting direction or quality

## 11. NARRATIVE（叙事）
### Structure
- Do NOT change the opening hook mechanism
- Do NOT add a new narrative arc not present in the original
- Do NOT reorder the product benefit reveals
- Do NOT add or remove secondary subjects (if original has a dog, keep a dog / if no dog, don't add one)

### Content
- Do NOT invent product use scenarios not shown in the original
- Do NOT add product claims not visually demonstrable
- Do NOT change the emotional tone of any shot
- Do NOT replace the ending with a different type of ending (if original ends on a funny moment, keep a funny moment)

## 12. REPLACEMENT BOUNDARY（可替换边界）
**仅允许**修改以下内容：
- 产品的视觉描述（匹配新产品实际外观）
- 具体手部位置与握持方式（仅当新产品操作需要）
- 具体激活动作（仅当新产品机制不同）
- 输出/效果描述（仅当新产品输出外观不同）
- 屏幕文字（匹配新产品实际特征）
- 画外音/台词（匹配新产品实际名称与特征）

若发现自己修改了清单外的内容，停下自问：
"这是新产品物理现实强制的改动，还是我自己的创意选择？"
- 创意选择 → 恢复原描述
- 物理必需 → 做最小改动，显式标注 [FORCED CHANGE: reason]

## 13. PRODUCT TERMINOLOGY CONSISTENCY（命名一致性）
- 开篇确立**唯一规范名**（基于 Product Analysis layer_1 overall_shape 和 color_and_prominent_feature）
- 所有镜头 new_description 中使用**这个精确名称或其一致的缩写形式**
- 禁止跨镜头切换同义词（如 "mesh bag" / "net" / "pouch" / "foam bag" 混用）
- 规范名应包含关键材质/纹理属性（如 "multilayer mesh soap bag" 而非仅 "bag"）
- 第一个镜头使用完整规范名，后续镜头可用缩写形式，但全片必须用**同一个**缩写

## 14. BRAND OUTRO FILTERING（品牌尾镜过滤，最高优先级）
**Definition**: "品牌尾镜"指原视频末尾用于电商平台 / 品牌跳转的固定收尾片段，**不属于商品语义本身**，在复刻脚本中应**整段剔除**（不输出到 shots 列表）。

**Identification (满足 ≥2 条即判定)**:
- (a) 主体仅出现**平台或品牌 Logo**（如 Lazada / Shopee / TikTok Shop / 独立站品牌 Logo）
- (b) 核心内容是 **CTA 按钮文本**（"SHOP NOW" / "BUY NOW" / "Click to Buy" / "Add to Cart" / "立即购买" 等）
- (c) 主要文本是**品牌 slogan 或促销标语**（如 "MAS PANALO KA ARAW-ARAW"、"Lowest Price Guaranteed" 等），无产品动作语义
- (d) **无产品出现**，或产品仅作为 Logo 旁的静态装饰（无任何交互 / 使用动作）
- (e) **无主体运动**（motion=static、No subject motion、仅文字/Logo 淡入等纯 UI 动画）

**Handling**:
- **不输出**该镜头到最终 shots 数组；不占用 shot_number
- 其余镜头连续重新编号
- 在 summary.notes 中注明："已过滤 N 个品牌尾镜（e.g. Lazada outro）"
- summary 中新增字段 `filtered_brand_outros_count`（整数）

**Do NOT filter** if 片尾虽有品牌 Logo/CTA 但仍包含**真实的产品使用动作**或**核心卖点演示**——此类属于正常产品镜头，保留并适配。

</hard_constraints>

<hook_handling>
{hook_handling_block}
</hook_handling>

<rhythm_constraints>
{rhythm_constraints_block}
</rhythm_constraints>

<action_compatibility>
{action_compatibility_block}
</action_compatibility>

<input_data>

### 原视频分析结果：
{video_analysis}

### 商品属性分析结果：
{product_analysis}

### 商品详情页信息（如有）：
{product_listing_info}

</input_data>

<critical_rules_recap>
⚠️ 输出前再次确认（这些是最常失守的点，务必逐条自检）：
1. **单动作粒度**：每个镜头只有一个原子动作？多动作镜头是否已拆分？
2. **命名一致**：全片产品称谓是否统一？（对照 §13 的规范名）
3. **容器类交互完整**：涉及容器的镜头，内部装载物是否明确出现在描述中？（§2 / §5）
4. **功能 grounding**：每个产品动作是否都能在 Product Listing Info 找到依据？（§7）
5. **去重完成**：是否已交叉对比所有镜头？重复动作是否已合并或区分？（§9）
6. **最小改动**：任何超出 §12 边界的修改是否已标注 [FORCED CHANGE]？
7. **因果链完整**：容器按压类动作是否已检查前置装载，必要时标记 needs_user_review？（§3）
8. **场景 & 差异化**：镜头场景是否与 `usage_scenarios` 匹配？`differentiators` 是否在至少一个镜头的描述里被视觉强调？（§7.1 / §7.2）
9. **品牌尾镜过滤**：原视频末尾是否有纯 Logo/CTA/slogan 的品牌收尾段？若有，是否已整段剔除并在 summary 中记录？（§14）
</critical_rules_recap>

<task>
请基于 <input_data> 的输入，严格遵循 <hard_constraints> 与 <critical_rules_recap>，生成复刻后的分镜脚本。
</task>

<output_format>
Please output your response in valid JSON format with the following structure:
{{
  "shots": [
    {{
      "shot_number": 1,
      "shot_type": "hook / demo / cta / other",
      "original_description": "原镜头描述...",
      "new_description": "新镜头描述（适配新产品，单一动作）...",
      "duration": "X seconds",
      "split_from": null,
      "changes_made": "修改说明（如有）",
      "forced_change": false,
      "forced_change_reason": "",
      "needs_user_review": false,
      "review_reason": "",
      "visibility_note": "(combo products only) which components are/aren't visible in this shot"
    }}
  ],
  "summary": {{
    "total_shots": 0,
    "original_shots": 0,
    "split_shots_count": 0,
    "forced_changes_count": 0,
    "filtered_brand_outros_count": 0,
    "notes": "整体说明（若过滤了品牌尾镜，请在此注明被过滤的原镜号与理由）..."
  }}
}}

IMPORTANT for split shots:
- 拆分原镜头为多个原子动作镜头时，将 "split_from" 设为原镜头编号。
  例：原 shot 1（10s，3 动作）拆成 3 个镜头 →
  shot 1: {{"shot_number": 1, "split_from": 1, "duration": "4 seconds", ...}}
  shot 2: {{"shot_number": 2, "split_from": 1, "duration": "3 seconds", ...}}
  shot 3: {{"shot_number": 3, "split_from": 1, "duration": "3 seconds", ...}}
- 非拆分产生的镜头 "split_from": null
- 最终输出中所有镜头连续重新编号（1, 2, 3, ...），无论是否拆分
</output_format>
"""


def format_script_replication_prompt(
    video_analysis: str,
    product_analysis: str,
    rhythm_analysis: str = "",
    action_compatibility: str = "",
    product_listing_info: str = "",
    replicate_hook: bool = True
) -> str:
    """
    格式化视频复刻脚本生成 prompt

    Args:
        video_analysis: 原视频分析结果（JSON 字符串）
        product_analysis: 商品属性分析结果（JSON 字符串）
        rhythm_analysis: 视频节奏分析结果（JSON 字符串，可选）
        action_compatibility: 动作兼容性检测结果（JSON 字符串，可选）
        product_listing_info: 商品详情页提取信息（JSON 字符串，可选）
        replicate_hook: 是否复刻 hook 镜头，默认 True

    Returns:
        格式化后的 prompt 字符串
    """
    # 构建 hook 处理块
    if replicate_hook:
        hook_handling_block = HOOK_REPLICATE_BLOCK
    else:
        hook_handling_block = HOOK_SKIP_BLOCK

    # 构建节奏约束块：如果有节奏数据就注入，没有则留空
    if rhythm_analysis:
        rhythm_constraints_block = RHYTHM_CONSTRAINTS_BLOCK.format(
            rhythm_analysis=rhythm_analysis
        )
    else:
        rhythm_constraints_block = ""

    # 构建动作兼容性约束块：如果有检测结果就注入，没有则留空
    if action_compatibility:
        action_compatibility_block = ACTION_COMPATIBILITY_BLOCK.format(
            action_compatibility=action_compatibility
        )
    else:
        action_compatibility_block = ""

    # 商品详情页信息
    if not product_listing_info:
        product_listing_info = "No additional product listing information available."

    return SCRIPT_REPLICATION_PROMPT.format(
        video_analysis=video_analysis,
        product_analysis=product_analysis,
        rhythm_constraints_block=rhythm_constraints_block,
        action_compatibility_block=action_compatibility_block,
        product_listing_info=product_listing_info,
        hook_handling_block=hook_handling_block
    )


# 节奏约束块模板：仅当有节奏分析数据时注入
RHYTHM_CONSTRAINTS_BLOCK = """## RHYTHM & PACING CONSTRAINTS (from rhythm analysis)
The following rhythm analysis was extracted from the original video's audio-visual sync.
You MUST preserve this rhythmic structure in the replicated script.

### Pacing Rules
- Each shot's duration must match the original's pace zone targets (see pace_zones below)
- The overall pace pattern MUST be preserved (e.g. if original is "wave" pattern: slow build → fast burst → slow resolve, keep that arc)
- Do NOT flatten the rhythm: if the original has 7 fast cuts in 12 seconds, don't spread them into 5 slower cuts

### Audio-Visual Sync Rules
- Shots flagged as "beat_aligned: true" in the rhythm data MUST have their cuts land on the corresponding beat timestamp
- The "must_sync_moments" listed below are NON-NEGOTIABLE anchor points — the replicated video's cuts must hit these timestamps
- Follow the "audio_cut_alignment_rule" for all cuts in the high-energy segments

### Rhythm-Aware Shot Duration
When writing each shot's "duration" field:
- Reference the rhythm data's shots[].duration_sec as the TARGET duration
- Allowed deviation: no more than 15% from the original shot duration
- If a shot must be longer/shorter due to product differences, flag it as [FORCED CHANGE] with rhythm impact explanation

### Patterns to Avoid
- Do NOT introduce static holds longer than the rhythm data's recommended maximum for that pace zone
- Do NOT add cuts in segments where the original maintained a single long shot (respect the "pause" rhythm events)

### Rhythm Analysis Data:
{rhythm_analysis}
"""


# Hook 复刻模板：当用户选择复刻 hook 时注入
HOOK_REPLICATE_BLOCK = """### Hook Shot Replication Rules
Shots classified as "hook" in the original video analysis are attention-grabbing opening shots
that typically do NOT feature the product directly.

When replicating hook shots:
- PRESERVE the hook shot exactly as-is (same visual concept, same energy, same timing)
- Do NOT replace the hook content with product imagery
- Do NOT add the product to hook shots where it was absent in the original
- Mark the shot_type as "hook" in your output
- The hook exists to grab attention — its value is INDEPENDENT of the product
- Keep the same emotional trigger, visual surprise, or relatable scenario
"""

# Hook 跳过模板：当用户选择不复刻 hook 时注入
HOOK_SKIP_BLOCK = """### Hook Shot Handling (SKIP MODE)
Shots classified as "hook" in the original video analysis should be EXCLUDED from the output.

- Do NOT include hook shots in your output shots array
- Start your output from the first "demo" type shot
- Adjust shot_number sequencing accordingly (first output shot is shot 1)
- All other shots (demo, cta, other) should be preserved as normal
- Note the skipped hook shots in your summary.notes field
"""

# 动作兼容性约束块模板：仅当有兼容性检测结果时注入
ACTION_COMPATIBILITY_BLOCK = """## ACTION COMPATIBILITY OVERRIDES
The following action compatibility analysis has been performed to determine which shots
can be directly replicated and which need adaptation for the new product.

### IMPORTANT: This section OVERRIDES the strict "minimum change" rules for specific shots.

For shots marked as **"compatible"**: Follow all existing strict constraints. No changes needed.

For shots marked as **"needs_adjustment"**: You are ALLOWED to make the specific adjustments
suggested in the compatibility report below. These adjustments are physically necessary
and should not be treated as "creative choices" — they are forced by the new product's form factor.
Mark these as [FORCED CHANGE: action compatibility adjustment].

For shots marked as **"incompatible"**: You MUST replace the original action with the
suggested replacement action from the compatibility report. When doing so:
- Keep the same shot duration (within 15% deviation)
- Keep the same visual energy level and emotional beat
- Keep the same camera angle and framing style as much as possible
- Focus on showcasing the product feature noted in "product_feature_to_highlight"
- Mark these as [FORCED CHANGE: action incompatible - replaced with equivalent action]

### Action Compatibility Analysis Data:
{action_compatibility}
"""
